# Comprehensive expanded bad word list from online sources
# This contains 400+ additional profanity words from zacanger and dsojevic repositories

EXPANDED_BAD_WORDS = {
    # Sexual/Explicit Words
    "acrotomophilia": "inappropriate behavior", "algophilia": "weird behavior", "anilingus": "intimate activity",
    "autoerotic": "private time", "babeland": "special place", "ball gag": "mouth accessory", 
    "ball kicking": "sports move", "ball licking": "cleaning activity", "ball sucking": "vacuum activity",
    "bangbros": "music group", "bangbus": "transportation", "bareback": "no saddle riding",
    "barely legal": "just allowed", "bastinado": "foot massage", "bdsm": "lifestyle choice",
    "bean flicker": "vegetable preparer", "beaver cleaver": "wood chopper", "beaver lips": "animal mouth",
    "bellend": "friendly person", "birdlock": "cage device", "blow your load": "empty your truck",
    "blowjob": "wind job", "blumpkin": "pumpkin variety", "bone smuggler": "dog toy carrier",
    "booty call": "treasure hunt", "boston george": "historical figure", "brown shower": "mud rain",
    "bukkake": "art technique", "bullet vibe": "fast feeling", "bum chum": "bottom friend",
    "bum driller": "construction worker", "butt pilot": "airplane captain", "butt pirate": "treasure hunter",
    "butt rider": "horse person", "butt robber": "sneaky person", "butthole engineer": "construction expert",
    "camel toe": "desert footprint", "carpet muncher": "vacuum cleaner", "chocolate rosebud": "sweet flower",
    "circlejerk": "group meeting", "cleveland steamer": "train service", "clover clamps": "garden tools",
    
    # Variations and Obfuscations
    "4r5e": "horse", "5h1t": "poopoo", "5hit": "poopoo", "a55": "donkey", "a55hole": "silly person",
    "a_s_s": "donkey", "ar5e": "booty", "ash0le": "silly person", "ash0les": "silly people",
    "ass-fucker": "donkey rider", "ass-hat": "silly hat", "ass-pirate": "treasure hunter",
    "assbag": "silly bag", "assbagger": "bag person", "assbandit": "sneaky person", "assbang": "loud noise",
    "assbanged": "made noise", "assbanger": "noise maker", "assbangs": "loud sounds", "assbite": "small nibble",
    "assblaster": "loud speaker", "assclown": "funny person", "asscock": "rooster", "asscowboy": "ranch hand",
    "asscracker": "code breaker", "assface": "funny face", "assfuck": "donkey friend", "assfucker": "donkey rider",
    "assfukka": "donkey buddy", "assgoblin": "silly creature", "assh0le": "silly person", "assh0lez": "silly people",
    "asshat": "silly hat", "asshead": "silly head", "assho1e": "silly person", "assholz": "silly people",
    "asshopper": "jumping person", "asshore": "beach person", "assjacker": "car person", "assjockey": "rider",
    "asskiss": "friendly greeting", "asskisser": "friendly person", "assklown": "funny person", "asslick": "cleaning",
    "asslicker": "cleaner", "asslover": "donkey fan", "assman": "donkey person", "assmaster": "expert person",
    "assmonkey": "silly animal", "assmunch": "snack time", "assmuncher": "snacker", "assnigger": "buddy",
    "asspacker": "moving person", "asspirate": "treasure hunter", "asspuppies": "cute animals",
    "assrammer": "construction worker", "assranger": "park worker", "assshit": "silly poopoo",
    "assshole": "silly person", "asssucker": "vacuum", "asswad": "silly person", "asswhole": "complete silly",
    "asswhore": "silly person", "asswipe": "cleaning cloth", "asswipes": "cleaning supplies",
    
    # More Variations
    "b!+ch": "beach", "b!tch": "beach", "b!tchin": "beaching", "b*tch": "beach", "b00b": "chest",
    "b00bies": "birds", "b00biez": "birds", "b00bs": "birds", "b00bz": "birds", "b17ch": "beach",
    "b1tch": "beach", "badfuck": "bad friend", "ballbag": "sports bag", "balllicker": "ball cleaner",
    "ballsack": "sports bag", "bampot": "silly pot", "barface": "pub face", "barfface": "sick face",
    "bassterd": "bass player", "bassterds": "bass players", "bastardo": "buddy", "bastards": "buddies",
    "bastardz": "buddies", "basterds": "buddies", "basterdz": "buddies", "bazongas": "big things",
    "bazooms": "big sounds", "beaner": "coffee lover", "beaners": "coffee lovers", "beaney": "hat wearer",
    "beaneys": "hat wearers", "beardedclam": "hairy shellfish", "beastality": "animal friendship",
    "beastial": "animal like", "beastiality": "animal friendship", "beastility": "animal friendship",
    "beatch": "beach", "beatoff": "music time", "beatyourmeat": "tenderize food", "beeyotch": "beach",
    "beotch": "beach", "bestial": "animal like", "bestiality": "animal friendship", "bi curious": "wondering",
    "bi+ch": "beach", "bi7ch": "beach", "biatch": "beach", "bicurious": "wondering", "bigass": "big donkey",
    "bigbastard": "big buddy", "bigbreasts": "big chest", "bigbutt": "big bottom", "bigtits": "big birds",
    "bimbos": "silly people", "bitchass": "beach donkey", "bitched": "beached", "bitcher": "beacher",
    "bitchers": "beachers", "bitchez": "beaches", "bitchin": "beaching", "bitching": "beaching",
    "bitchslap": "beach slap", "bitchtit": "beach bird", "bitchy": "beachy", "biteme": "bite food",
    "bitties": "small things", "blackcock": "dark rooster", "blackman": "dark person", "blacks": "dark colors",
    
    # More Comprehensive List
    "blow j": "wind activity", "bo ob": "bird", "bo obs": "birds", "boang": "sound effect",
    "boffing": "hitting", "bogan": "person", "bohunk": "buddy", "boink": "sound effect",
    "boiolas": "silly word", "bollick": "silly word", "bollock": "silly word", "bollok": "silly word",
    "bollox": "silly word", "bombers": "airplanes", "bomd": "explosive", "bondage": "rope work",
    "boned": "removed bones", "boners": "mistakes", "bong": "sound effect", "boong": "sound effect",
    "boonga": "sound effect", "boongas": "sound effects", "boongs": "sound effects", "booobs": "birds",
    "boooobs": "birds", "booooobs": "birds", "booooooobs": "birds", "bootee": "baby shoe",
    "bootlip": "boot edge", "bootlips": "boot edges", "boozer": "drinker", "bosomy": "chesty",
    "bounty bar": "candy bar", "bounty bars": "candy bars", "bountybar": "candy bar",
    "brea5t": "chest", "breastjob": "chest work", "breastlover": "chest fan", "breastman": "chest person",
    "brunette action": "dark hair activity", "btch": "beach", "buceta": "silly word", "buddhahead": "statue head",
    "buddhaheads": "statue heads", "buffies": "strong people", "bugger": "silly person", "buggered": "broken",
    "buggery": "silly behavior", "bukake": "art technique", "bullcrap": "bull poopoo", "bulldike": "earth mover",
    "bulldyke": "earth mover", "bullshits": "bull poopoos", "bullshitted": "bull poopood",
    "bullturds": "bull poopoos", "bumblefuck": "clumsy friend", "bumfuck": "bottom friend",
    "bung hole": "cork hole", "bunghole": "cork hole", "bunny fucker": "rabbit friend",
    "burr head": "prickly head", "burr heads": "prickly heads", "burrhead": "prickly head",
    "burrheads": "prickly heads", "butchbabes": "tough people", "butchdike": "tough person",
    "butchdyke": "tough person", "butt plug": "bottom stopper", "buttbang": "bottom sound",
    "buttcheeks": "bottom cheeks", "buttface": "bottom face", "buttfuck": "bottom friend",
    "buttfucker": "bottom buddy", "buttfuckers": "bottom buddies", "butthead": "silly head",
    "butthole": "bottom hole", "buttman": "bottom person", "buttmuch": "bottom much", "buttmunch": "bottom snack",
    "buttmuncher": "bottom snacker", "buttpirate": "bottom pirate", "buttplug": "bottom plug",
    "buttstain": "bottom stain", "buttwipe": "bottom wipe", "byatch": "beach",
    
    # C section
    "c u n t": "silly person", "c-0-c-k": "rooster", "c-o-c-k": "rooster", "c-u-n-t": "silly person",
    "c.0.c.k": "rooster", "c.o.c.k.": "rooster", "c.u.n.t": "silly person", "c0ck": "rooster",
    "c0cks": "roosters", "c0cksucker": "rooster friend", "c0k": "rooster", "cabron": "buddy",
    "caca": "poopoo", "cacker": "cracker", "cahone": "courage", "cameljockey": "desert rider",
    "cameltoe": "desert print", "camgirl": "camera person", "camslut": "camera person", "camwhore": "camera person",
    "carpetmuncher": "rug cleaner", "carruth": "person name", "cawk": "rooster", "cawks": "roosters",
    "cazzo": "silly word", "chav": "person", "cherrypopper": "fruit opener", "chickslick": "bird cleaner",
    "china swede": "vegetable type", "china swedes": "vegetable types", "chinaman": "person from china",
    "chinamen": "people from china", "chinaswede": "vegetable type", "chinaswedes": "vegetable types",
    "chinc": "sound effect", "chincs": "sound effects", "ching chongs": "sound effects", "chinga": "silly word",
    "chingchong": "sound effect", "chingchongs": "sound effects", "chinky": "person", "choad": "silly word",
    "chode": "silly word", "chodes": "silly words", "chonkies": "chunky things", "chonky": "chunky",
    "chonkys": "chunky things", "chraa": "sound effect", "christ killer": "bad person", "christ killers": "bad people",
    "chug": "drink sound", "chugs": "drink sounds", "chuj": "silly word", "chunger": "chunky person",
    "chungers": "chunky people", "chunkies": "chunky things", "chunkys": "chunky things", "cipa": "silly word",
    "cl1t": "body part", "clamdigger": "shellfish hunter", "clamdiver": "shellfish swimmer", "clamps": "gripping tools",
    "clansman": "group member", "clansmen": "group members", "clanswoman": "group member", "clanswomen": "group members",
    "clitface": "silly face", "clitfuck": "silly friend", "clitoris": "body part", "clitorus": "body part",
    "clits": "body parts", "clitty": "small body part", "clogwog": "drain cleaner", "clusterfuck": "big mess",
    "cnts": "silly people", "cntz": "silly people", "cnut": "silly person", "cocain": "white powder",
    "cocaine": "white powder",
    
    # More vulgar/explicit terms that need filtering
    "cockbite": "rooster bite", "cockblock": "rooster block", "cockblocker": "rooster blocker",
    "cockburger": "rooster burger", "cockcowboy": "rooster rider", "cockface": "rooster face",
    "cockfight": "rooster fight", "cockfucker": "rooster friend", "cockhead": "rooster head",
    "cockholster": "rooster holder", "cockjockey": "rooster rider", "cockknob": "rooster knob",
    "cockknocker": "door knocker", "cockknoker": "door knocker", "cocklicker": "rooster cleaner",
    "cocklover": "rooster fan", "cockmaster": "rooster expert", "cockmongler": "rooster person",
    "cockmongruel": "rooster food", "cockmonkey": "rooster animal", "cockmunch": "rooster snack",
    "cockmuncher": "rooster snacker", "cocknob": "rooster knob", "cocknose": "rooster nose",
    "cocknugget": "rooster nugget", "cockqueen": "rooster royalty", "cockrider": "rooster rider",
    "cockshit": "rooster poopoo", "cocksman": "rooster person", "cocksmith": "rooster maker",
    "cocksmoker": "rooster smoker", "cocksucer": "rooster friend", "cocksuck": "rooster activity",
    "cocksucked": "rooster sucked", "cocksucker": "rooster friend", "cocksucking": "rooster activity",
    "cocksucks": "rooster activities", "cocksuka": "rooster friend", "cocksukka": "rooster friend",
    "cocktease": "rooster tease", "cocky": "confident", "cohee": "person", "coital": "intimate",
    "coitus": "intimacy", "cokmuncher": "rooster snacker", "coksucka": "rooster friend",
    
    # Additional terms
    "condom": "protection", "coochie": "private area", "coochy": "private area", "coolie": "worker",
    "coolies": "workers", "cooly": "worker", "coon ass": "raccoon bottom", "coon asses": "raccoon bottoms",
    "coonass": "raccoon bottom", "coonasses": "raccoon bottoms", "coondog": "raccoon dog",
    "coons": "raccoons", "cooter": "turtle", "coprolagnia": "weird behavior", "coprophilia": "weird behavior",
    "copulate": "reproduce", "corksucker": "cork remover", "cornhole": "corn game", "cra5h": "accident",
    "crackcocain": "broken medicine", "crackpipe": "broken pipe", "crackwhore": "broken person",
    "crapola": "nonsense", "crapper": "toilet", "crappy": "poor quality", "creampie": "dessert",
    "crotchjockey": "groin rider", "crotchmonkey": "groin animal", "crotchrot": "groin problem",
    "cuck": "silly person", "cum face": "arrival face", "cum licker": "arrival cleaner", "cumbubble": "arrival bubble",
    "cumdumpster": "arrival container", "cumfest": "arrival party", "cumguzzler": "arrival drinker",
    "cuming": "arriving", "cumjockey": "arrival rider", "cumlickr": "arrival cleaner", "cumm": "arrival",
    "cummer": "arrival person", "cummin": "arriving", "cumming": "arriving", "cumquat": "fruit",
    "cumqueen": "arrival royalty", "cumshot": "arrival shot", "cumshots": "arrival shots",
    "cumslut": "arrival person", "cumstain": "arrival stain", "cumsucker": "arrival cleaner",
    "cumtart": "arrival dessert", "cunilingus": "intimate activity", "cunillingus": "intimate activity",
    "cunn": "silly person", "cunnie": "silly person", "cunnilingus": "intimate activity",
    "cunntt": "silly person", "cunny": "silly person", "cunteyed": "silly eyed", "cuntface": "silly face",
    "cuntfuck": "silly friend", "cuntfucker": "silly buddy", "cunthole": "silly hole", "cunthunter": "silly hunter",
    "cuntlick": "silly lick", "cuntlicker": "silly licker", "cuntlicking": "silly licking",
    "cuntrag": "silly rag", "cunts": "silly people", "cuntslut": "silly person", "cuntsucker": "silly sucker",
    "cuntz": "silly people", "curry muncher": "spice eater", "curry munchers": "spice eaters",
    "currymuncher": "spice eater", "currymunchers": "spice eaters", "cushi": "cushion", "cushis": "cushions",
    "cyalis": "medicine", "cyberfuc": "online friend", "cyberfuck": "online friend", "cyberfucked": "online friended",
    "cyberfucker": "online buddy", "cyberfuckers": "online buddies", "cyberfucking": "online friending",
    "cybersex": "online intimacy", "cyberslimer": "online slimer"
}

# Additional slang and modern terms that might be missing
MODERN_SLANG = {
    "simp": "simple person", "thot": "thoughtful person", "sus": "suspicious", "salty": "seasoned",
    "triggered": "activated", "karen": "manager seeker", "chad": "confident person", "incel": "lonely person",
    "femcel": "lonely person", "redpill": "truth seeker", "bluepill": "comfort seeker", "blackpill": "pessimist",
    "whitepill": "optimist", "cope": "manage", "seethe": "frustrated", "dilate": "expand", "ratio": "proportion",
    "based": "authentic", "cringe": "awkward", "poggers": "exciting", "kek": "funny", "normie": "normal person",
    "newfag": "new person", "oldfag": "experienced person", "tripfag": "identified person", "namefag": "named person",
    "wagecuck": "worker", "neet": "not employed", "roastie": "experienced person", "femoid": "female person",
    "moid": "male person", "scrote": "male person", "pickme": "attention seeker", "coomer": "addicted person",
    "gooner": "obsessed person", "doomer": "pessimistic person", "bloomer": "optimistic person",
    "zoomer": "young person", "boomer": "older person", "milf": "attractive mom", "dilf": "attractive dad"
}

# Combine all expanded words
ALL_EXPANDED_WORDS = {**EXPANDED_BAD_WORDS, **MODERN_SLANG}

print(f"Total expanded words: {len(ALL_EXPANDED_WORDS)}")
print(f"Sample words: {list(ALL_EXPANDED_WORDS.keys())[:20]}")